### PR TITLE
Unicode Decoding in String/Char Literal Evaluation

### PR DESCRIPTION
**Pull request by morris821028**
This patch is used to avoid the content of comment make it failed in parser. According to https://github.com/pejobo/beanshell2/issues/112 , there is a solution which move the unicode decode part of `readchar()` into `stringSetup` and `charSetup`.

### CODE REVIEW

**Comment by pejobo** [comment]
Thanks for making a pull request! This reminds me to add a "code of conduct", still on my buckt list :(

Two things before I proceed:
1. The pull request should be for branch v2.1, not master
2. I intend to change the licence to Apache-2, so please withdraw your pull request if you do not agree that your code is made available under this licence (see #110)

Another thing - do you know this repro: https://github.com/beanshell/beanshell?

**Comment by morris821028** [comment]
Yeah, I know the repo https://github.com/beanshell/beanshell . Therefore, I also opened the issue about it.  There are many enhancement in other repo than this one. But, this one has a large version number of release product.  I don't know what this repo has, but anthoer don't. Our product uses 2.1.x version, so there is a problem to update. 

Althrough @stain, @nickl- , etc. fixed some bugs in their repo, I prefer this repo to work with Eclipse IDE. It has more convenient to develop, experiment and build.

If all of you can decide how to merge into a repository, and create a complete environment for build flow and introduce what's kind of IDE you used, it will be more maintainers I think.

**Comment by morris821028** [comment]
Maybe we should limit some syntax problem.  Please look at https://stackoverflow.com/questions/30727515/why-is-executing-java-code-in-comments-with-certain-unicode-characters-allowed

**Comment by pejobo** [comment]
Superseded by #114

**Comment by nickl-** [comment]
@morris821028  pong!

Missed this thread but perhaps #110 is more appropriate for a response from me. @pejobo  please see response there...

**Pull request closed without merging**
